export const copyVi = {
  brand: {
    name: "NEXUS OS",
    subtitle: "Không gian làm việc cá nhân của Hưng Trần",
    owner: "Hưng Trần",
  },
  nav: {
    dashboard: "Trung tâm",
    expenses: "Chi tiêu",
    goals: "Mục tiêu",
    videoPlan: "Kế hoạch video",
    weeklyReview: "Tổng kết tuần",
    accounts: "Tài khoản",
    settings: "Cài đặt",
  },
  routeMeta: {
    auth: {
      title: "Xin chào Hưng Trần",
      subtitle: "Đăng nhập để tiếp tục",
    },
    dashboard: {
      title: "Trung tâm",
      subtitle: "Ưu tiên video, mục tiêu và tài chính mỗi ngày",
    },
    expenses: {
      title: "Chi tiêu",
      subtitle: "Theo dõi và tối ưu dòng tiền",
    },
    goals: {
      title: "Mục tiêu & Động lực",
      subtitle: "Duy trì tiến độ mỗi ngày",
    },
    "video-plan": {
      title: "Kế hoạch video",
      subtitle: "Điều phối workflow YouTube 6 bước",
    },
    "weekly-review": {
      title: "Tổng kết tuần",
      subtitle: "Nhìn lại tuần cũ và chốt kế hoạch tuần mới",
    },
    accounts: {
      title: "Tài khoản",
      subtitle: "Quản lý số dư và luồng tiền",
    },
    settings: {
      title: "Cài đặt",
      subtitle: "Hồ sơ và tùy chọn cá nhân",
    },
  },
  common: {
    guest: "Khách",
    month: "Tháng",
    loading: "Đang tải dữ liệu...",
    noData: "Chưa có dữ liệu",
    allAccounts: "Tất cả tài khoản",
    save: "Lưu",
    cancel: "Hủy",
    delete: "Xóa",
    edit: "Sửa",
    close: "Đóng",
    apply: "Áp dụng",
    reset: "Đặt lại",
  },
  cta: {
    addExpense: "+ Thêm khoản chi",
    addGoal: "Mở mục tiêu hôm nay",
    addVideoTask: "Thêm công việc video",
    weeklyReview: "Tổng kết tuần",
    openVideoBoard: "Mở bảng video",
    checkIn: "Điểm danh",
  },
  dashboard: {
    hero: {
      greeting: {
        morning: "Chào buổi sáng, {{name}}",
        afternoon: "Chào buổi chiều, {{name}}",
        evening: "Chào buổi tối, {{name}}",
      },
      missionTitle: "Nhiệm vụ hôm nay",
      missionDefault: "Hoàn thành 1 mục tiêu và đẩy 1 công việc video tiến lên trong hôm nay.",
      missionHabit: "Bạn còn {{count}} lượt thói quen cần hoàn thành trong kỳ hiện tại.",
      missionVideo: "Bạn còn {{count}} công việc video chưa xuất bản. Ưu tiên đẩy sang bước kế tiếp.",
      quickActionsTitle: "Hành động nhanh",
      meta: "Trạng thái theo thời gian thực của tháng đang chọn",
    },
    priority: {
      title: "Ưu tiên hôm nay",
      empty: "Không có việc gấp cần xử lý ngay.",
      habitMeta: "{{done}}/{{target}} lượt • {{period}}",
      videoMetaNoDue: "Video chưa có hạn • {{stage}}",
      videoMetaDue: "Hạn {{dueDate}} • {{stage}}",
      actionCheckIn: "Điểm danh",
      actionOpenVideo: "Mở bảng video",
    },
    actionBoard: {
      title: "Bảng hành động hôm nay",
      subtitle: "Tập trung vào việc kế tiếp và các công việc video cận hạn {{hours}} giờ.",
      nextTitle: "Việc kế tiếp",
      deadlineTitle: "Cận hạn {{hours}} giờ",
      summaryTitle: "Tóm tắt hành động",
      emptyNext: "Không còn việc ưu tiên cần xử lý ngay.",
      emptyDeadline: "Không có công việc video cận hạn trong {{hours}} giờ tới.",
      summary: "Hôm nay còn {{habitCount}} lượt thói quen và {{videoCount}} công việc video mở.",
      summaryDone: "Hôm nay không có việc khẩn cấp.",
      quickCheckin: "Điểm danh ngay",
      quickOpenDeadline: "Mở việc cận hạn",
    },
    nextAction: {
      habitBadge: "Thói quen",
      videoBadge: "Video",
      actionCheckIn: "Điểm danh",
      actionOpenVideo: "Mở công việc",
      actionOpenBoard: "Mở bảng",
      habitMeta: "{{remaining}} lượt còn lại • {{period}}",
      videoMetaDue: "Hạn {{dueDate}} • {{stage}}",
      videoMetaNoDue: "Chưa có hạn • {{stage}}",
    },
    deadline: {
      dueLabel: "Hạn {{dueDate}}",
      stageLabel: "Giai đoạn: {{stage}}",
    },
    reminder: {
      overdue: "Quá hạn {{count}}",
      today: "Hôm nay {{count}}",
      soon: "Cận hạn {{hours}}h {{count}}",
      overdueLabel: "Quá hạn",
      todayLabel: "Hôm nay",
      soonLabel: "Cận hạn",
    },
    modules: {
      video: {
        title: "Luồng video tuần này",
        subtitle: "Ưu tiên xử lý các công việc sắp tới hạn.",
        link: "Mở bảng",
      },
      goals: {
        title: "Mục tiêu đang chạy",
        subtitle: "Theo dõi tiến độ và hoàn thành mục tiêu trọng tâm.",
        link: "Mở chi tiết",
      },
      motivation: {
        title: "Động lực",
        subtitle: "Thử thách ngày/tuần/tháng + XP + cấp độ.",
        link: "Xem thử thách",
      },
      accounts: {
        title: "Số dư tài khoản",
        empty: "Chưa có dữ liệu số dư tài khoản.",
      },
    },
    heroKpi: {
      videoOpen: "Việc video đang mở",
      habitLeft: "Lượt thói quen còn lại",
      activeGoals: "Mục tiêu đang chạy",
    },
  },
  goals: {
    status: {
      done: "Hoàn thành",
      active: "Đang chạy",
      reached: "Đã đạt",
    },
    table: {
      emptyGoals: "Chưa có mục tiêu nào.",
      emptyHabits: "Chưa có thói quen nào.",
    },
    dailyFocus: {
      title: "Hôm nay cần làm gì",
      subtitle: "Ưu tiên các thói quen còn thiếu quota để giữ chuỗi ngày.",
      empty: "Tuyệt vời! Bạn đã hoàn thành toàn bộ quota kỳ hiện tại.",
      action: "Điểm danh nhanh",
      remaining: "Còn {{remaining}} lượt",
    },
  },
  videoPlan: {
    filters: {
      title: "Bộ lọc bảng",
      stageAll: "Tất cả giai đoạn",
      priorityAll: "Tất cả ưu tiên",
      queryPlaceholder: "Tìm theo tiêu đề hoặc ghi chú...",
      reset: "Đặt lại",
      summary: "{{filtered}}/{{total}} công việc đang hiển thị",
    },
    form: {
      addTitle: "Tạo công việc video mới",
      editTitle: "Chỉnh sửa công việc video",
      noDeadline: "Không hạn",
      noNote: "Không có ghi chú",
      emptyBoard: "Chưa có công việc phù hợp bộ lọc.",
      emptySummary: "Chưa có công việc video.",
    },
    stage: {
      idea: "Ý tưởng",
      research: "Nghiên cứu",
      script: "Kịch bản",
      shoot: "Quay",
      edit: "Dựng",
      publish: "Xuất bản",
    },
    priority: {
      low: "Thấp",
      medium: "Vừa",
      high: "Cao",
    },
    calendar: {
      monthFallback: "Tháng hiện tại",
      selectedDate: "Lịch ngày {{date}}",
      selectedDateFallback: "Lịch theo ngày",
      count: "{{count}} việc",
      overdueCount: "Quá hạn {{count}}",
      openTask: "Mở công việc",
      empty: "Chưa có lịch video cho tháng đang chọn.",
      emptyDay: "Ngày này chưa có công việc video.",
      emptyUnscheduled: "Không có công việc chưa lên lịch.",
    },
    reminder: {
      overdue: "Quá hạn: {{count}}",
      today: "Hôm nay: {{count}}",
      soon: "Cận hạn {{hours}}h: {{count}}",
    },
  },
  ai: {
    common: {
      apply: "Áp dụng toàn bộ",
      cooldown: "Thử lại sau {{sec}}s",
      cooldownToast: "Vui lòng chờ {{sec}} giây trước khi gọi AI tiếp theo.",
    },
    expenseLabel: {
      suggested: "AI đề xuất danh mục {{category}} (độ tin cậy {{confidence}}).",
      autoApplied: "AI đã tự gán danh mục {{category}} ({{confidence}}).",
      manualApplied: "Đã áp dụng danh mục {{category}} từ gợi ý AI.",
      errorHint: "Chưa thể gợi ý danh mục lúc này. Bạn vẫn có thể chọn thủ công.",
    },
    videoCopilot: {
      generate: "AI gợi ý mới",
      improve: "AI cải thiện nội dung",
      generateLoading: "Đang tạo gợi ý...",
      improveLoading: "Đang cải thiện...",
      empty: "Bấm AI gợi ý để nhận phương án video theo ngữ cảnh hiện tại.",
      optionUntitled: "Phương án chưa có tiêu đề",
      optionIndex: "Ph\u01b0\u01a1ng \u00e1n {{index}}",
      deadline: "Hạn gợi ý",
      noDeadline: "Không có hạn gợi ý",
      reasonLabel: "L\u00fd do g\u1ee3i \u00fd",
      shotListLabel: "Danh s\u00e1ch c\u1ea3nh quay",
      noteLabel: "Ghi ch\u00fa tri\u1ec3n khai",
    },
    goalCopilot: {
      generate: "AI gợi ý mới",
      improve: "AI cải thiện nội dung",
      generateLoading: "Đang tạo gợi ý...",
      improveLoading: "Đang cải thiện...",
      empty: "Bấm AI gợi ý để nhận bundle mục tiêu và thói quen phù hợp.",
      optionUntitled: "Mục tiêu chưa có tên",
      habitUntitled: "Thói quen chưa có tên",
      habitLabel: "Thói quen đi kèm",
    },
  },
  weeklyReview: {
    header: {
      title: "Tổng kết tuần",
      subtitle: "Nghi thức review cuối tuần để ra quyết định nhanh cho tuần mới.",
      weekLabel: "Tuần {{weekKey}} • {{range}}",
      fallbackWeek: "Tuần hiện tại",
    },
    cards: {
      finance: "Tài chính tuần",
      goals: "Mục tiêu & thói quen",
      video: "Video tuần này",
      motivation: "Động lực tuần",
    },
    finance: {
      income: "Tổng thu",
      expense: "Tổng chi",
      net: "Dòng tiền ròng",
      transfer: "Chuyển khoản nội bộ",
      transactions: "Số giao dịch",
    },
    goals: {
      active: "Mục tiêu đang chạy",
      done: "Mục tiêu đã hoàn thành",
      habitsTotal: "Thói quen đang theo dõi",
      habitsReached: "Thói quen đạt quota",
      checkins: "Lượt điểm danh",
    },
    video: {
      open: "Công việc đang mở",
      done: "Công việc đã xong",
      dueWeek: "Công việc có hạn trong tuần",
      dueWindow: "Công việc cận hạn {{hours}}h",
      overdue: "Công việc quá hạn",
    },
    motivation: {
      streak: "Chuỗi ngày",
      totalXp: "Tổng XP",
      level: "Cấp độ",
      weekXp: "XP trong tuần",
      challengeWeek: "Thử thách tuần",
    },
    plan: {
      title: "Kế hoạch tuần mới",
      focusTheme: "Chủ đề trọng tâm",
      priority1: "Ưu tiên 1",
      priority2: "Ưu tiên 2",
      priority3: "Ưu tiên 3",
      riskNote: "Rủi ro cần lưu ý",
      actionCommitments: "Cam kết hành động",
      save: "Lưu tổng kết tuần",
    },
    history: {
      title: "Lịch sử review gần đây",
      empty: "Chưa có lịch sử tổng kết tuần.",
      hasPlan: "Đã có kế hoạch",
      noPlan: "Chưa có kế hoạch",
    },
    status: {
      idle: "Sẵn sàng tổng kết tuần",
      saving: "Đang lưu...",
      saved: "Đã lưu",
      savedAt: "Đã lưu lúc {{time}}",
      error: "Lưu thất bại",
    },
  },
  settings: {
    tabs: {
      profile: "Hồ sơ cá nhân",
      dashboard: "Tùy chọn Dashboard",
      filters: "Bộ lọc & Hiển thị",
    },
    profile: {
      title: "Hồ sơ cá nhân",
      subtitle: "Thông tin này ảnh hưởng trực tiếp đến dashboard cá nhân hóa.",
      displayName: "Tên hiển thị",
      displayNamePlaceholder: "Ví dụ: Hưng Trần",
      tagline: "Tagline",
      taglinePlaceholder: "Ví dụ: Tập trung tăng trưởng nội dung đều mỗi tuần",
      missionDefault: "Nhiệm vụ mặc định",
      missionDefaultPlaceholder: "Ví dụ: Hoàn thành 1 bước video và 1 hành động tài chính",
    },
    preferences: {
      dashboard: {
        title: "Tùy chọn Dashboard",
        nextActionsMax: "Số việc kế tiếp hiển thị",
        deadlineWindowHours: "Khung giờ cảnh báo cận hạn",
        startRoute: "Route mặc định sau đăng nhập",
        startRouteOptions: {
          dashboard: "Trung tâm",
          goals: "Mục tiêu",
          videoPlan: "Kế hoạch video",
        },
      },
      filters: {
        title: "Bộ lọc & Hiển thị",
        monthMode: "Chế độ tháng mặc định",
        monthModeOptions: {
          current: "Luôn về tháng hiện tại",
          lastUsed: "Nhớ tháng đã dùng gần nhất",
        },
        rememberExpenseFilters: "Nhớ bộ lọc Chi tiêu",
        rememberIncomeFilters: "Nhớ bộ lọc Thu nhập",
        rememberVideoFilters: "Nhớ bộ lọc Video",
      },
      ui: {
        density: "Mật độ giao diện",
        densityOptions: {
          comfortable: "Thoải mái",
          compact: "Gọn",
        },
      },
    },
    status: {
      saving: "Đang lưu...",
      saved: "Đã lưu",
      savedAt: "Đã lưu lúc {{time}}",
      error: "Lưu thất bại",
      idle: "Thay đổi sẽ tự động lưu",
    },
    toast: {
      saveSuccess: "Đã lưu cài đặt.",
      saveFail: "Không thể lưu cài đặt. Hệ thống sẽ thử lại ở lần thay đổi tiếp theo.",
    },
  },
  accounts: {
    transfer: "Chuyển tiền",
    addIncome: "Thêm thu nhập",
    addAccount: "Thêm tài khoản",
    validation: {
      nameRequired: "Vui lòng nhập tên tài khoản",
      nameDuplicate: "Tên tài khoản đã tồn tại",
      idMissing: "Thiếu ID tài khoản",
      nameEmpty: "Tên tài khoản không được để trống",
      deleteIdMissing: "Thiếu ID tài khoản cần xóa",
      reassignRequired: "Vui lòng chọn tài khoản để chuyển dữ liệu",
      transferAccountsRequired: "Vui lòng chọn đầy đủ tài khoản",
      transferAccountDifferent: "Tài khoản chuyển và nhận phải khác nhau",
      transferAmountRequired: "Vui lòng nhập số tiền",
      transferAmountInvalid: "Số tiền không hợp lệ",
      transferDateRequired: "Vui lòng chọn ngày",
    },
    toast: {
      addSuccess: "Đã thêm tài khoản mới",
      addFail: "Không thể thêm tài khoản",
      updateSuccess: "Đã cập nhật tài khoản",
      updateFail: "Không thể cập nhật tài khoản",
      deleteSuccess: "Đã xóa tài khoản",
      deleteFail: "Không thể xóa tài khoản",
      transferSuccess: "Đã chuyển tiền giữa các tài khoản",
      transferFail: "Không thể chuyển tiền",
    },
  },
  emptyState: {
    goals: "Chưa có mục tiêu đang chạy.",
    motivation: "Chưa có dữ liệu động lực.",
    video: "Chưa có công việc video.",
  },
  toast: {
    signInRequired: "Vui lòng đăng nhập trước",
    loadFail: "Không thể tải dữ liệu. Vui lòng thử lại.",
    deleteDataFail: "Không thể xóa dữ liệu",
    expenseAdded: "Đã thêm khoản chi.",
    expenseUpdated: "Đã cập nhật khoản chi.",
    expenseDeleted: "Đã xóa khoản chi.",
    expenseCreateFail: "Không thể thêm khoản chi",
    expenseUpdateFail: "Không thể cập nhật khoản chi",
    expenseNotFound: "Không tìm thấy khoản chi",
    expenseOpenFail: "Không thể mở khoản chi",
    incomeAdded: "Đã thêm khoản thu.",
    incomeUpdated: "Đã cập nhật khoản thu.",
    incomeDeleted: "Đã xóa khoản thu.",
    incomeCreateFail: "Không thể thêm khoản thu",
    incomeUpdateFail: "Không thể cập nhật khoản thu",
    incomeNotFound: "Không tìm thấy khoản thu",
    incomeOpenFail: "Không thể mở khoản thu",
    csvExportFail: "Xuất CSV thất bại.",
    csvExportSuccess: "Đã xuất CSV tháng hiện tại.",
    goalAdded: "Đã tạo mục tiêu mới.",
    goalCreateFail: "Không thể tạo mục tiêu",
    goalProgressUpdated: "Đã cập nhật tiến độ mục tiêu.",
    goalDoneXp: "Đã hoàn thành mục tiêu. +120 XP",
    goalDeleted: "Đã xóa mục tiêu.",
    goalUpdateFail: "Không thể cập nhật mục tiêu",
    habitAdded: "Đã tạo thói quen mới.",
    habitCreateFail: "Không thể tạo thói quen",
    habitNotFound: "Không tìm thấy thói quen",
    habitLocked: "Bạn đã đạt mục tiêu kỳ này",
    habitChecked: "Điểm danh thành công. +{{xp}} XP",
    habitDeleted: "Đã xóa thói quen.",
    habitUpdateFail: "Không thể cập nhật thói quen",
    videoAdded: "Đã thêm công việc video mới.",
    videoUpdated: "Đã cập nhật công việc video.",
    videoNotFound: "Không tìm thấy công việc video",
    videoDeleted: "Đã xóa công việc video.",
    videoCreateFail: "Không thể tạo công việc video",
    videoUpdateFail: "Không thể cập nhật công việc video",
    videoDeleteFail: "Không thể xóa công việc video",
    videoMoved: "Đã chuyển bước công việc video.",
    videoMoveFail: "Không thể chuyển bước",
    videoFilterSaved: "Đã cập nhật bộ lọc video.",
    videoAiReady: "AI đã tạo 3 phương án video.",
    videoAiFallback:
      "AI đang dùng mẫu gợi ý cục bộ. Bạn vẫn có thể bấm tạo lại để lấy phương án mới.",
    videoAiFail: "Không thể tạo gợi ý video lúc này.",
    videoAiApplied: "Đã áp dụng phương án AI vào form video.",
    goalAiReady: "AI đã tạo 3 bundle mục tiêu.",
    goalAiFail: "Không thể tạo gợi ý mục tiêu lúc này.",
    goalAiApplied: "Đã áp dụng bundle AI vào form mục tiêu.",
    weeklyReviewSaved: "Đã lưu tổng kết tuần.",
    weeklyReviewSaveFail: "Không thể lưu tổng kết tuần.",
  },
};

export function t(path, fallback = "") {
  if (!path) return fallback;

  const chunks = String(path).split(".");
  let cur = copyVi;

  for (const key of chunks) {
    if (cur && Object.prototype.hasOwnProperty.call(cur, key)) {
      cur = cur[key];
    } else {
      return fallback;
    }
  }

  return cur ?? fallback;
}

export function formatTemplate(template, payload = {}) {
  let out = String(template || "");
  Object.entries(payload).forEach(([k, v]) => {
    out = out.replaceAll(`{{${k}}}`, String(v ?? ""));
  });
  return out;
}
