export const copyVi = {
  brand: {
    name: "Hung Tran Finance",
    shortName: "HT Finance",
    tagline: "Tài chính cá nhân",
    owner: "Hưng Trần",
  },
  nav: {
    home: "Tổng quan",
    homeShort: "Tổng",
    ledger: "Chi tiêu",
    overview: "Tổng quan",
    expenses: "Chi tiêu",
    loans: "Cho mượn",
    reports: "Báo cáo",
  },
  routeMeta: {
    auth: {
      title: "Đăng nhập",
      subtitle: "Đăng nhập Google để vào tài khoản của bạn",
    },
    home: {
      title: "Tổng quan",
      subtitle: "Số dư, nhắc nhở và giao dịch gần đây trong một màn hình.",
    },
    expenses: {
      title: "Chi tiêu",
      subtitle: "Ghi và tìm mọi khoản chi, thu, chuyển.",
    },
    loans: {
      title: "Cho mượn",
      subtitle: "Theo dõi tiền cho mượn và tiền được trả lại theo từng người.",
    },
    overview: {
      title: "Tổng quan",
      subtitle: "Nhìn nhanh số dư và tình hình chi tiêu tháng này.",
    },
    reports: {
      title: "Báo cáo",
      subtitle: "Phân tích chi tiêu theo kỳ bạn chọn.",
    },
  },
  glossary: {
    expenseTab: "Chi tiêu",
    scopeGroup: "Nhóm chi",
    scopeGroupManage: "Thêm / sửa nhóm",
    adjustment: "Sửa số dư",
    pickDate: "Chọn ngày",
    ledger: "Giao dịch",
    netBalance: "Còn lại",
    netBalanceNote: "Thu − Chi",
    loanOutstanding: "Tiền cho mượn",
    monthSummary: "Tóm tắt tháng",
    periodSummary: "Tóm tắt kỳ",
    worthNoting: "Điểm đáng lưu ý",
    topCategories: "Top danh mục chi",
    recentTransactions: "Giao dịch gần đây",
    viewAllTransactions: "Xem tất cả",
    openLedger: "Mở chi tiêu",
    fullReport: "Báo cáo",
    reportDetail: "Báo cáo chi tiết",
    expenseOnly: "Chỉ khoản chi",
    topScope: "Nhóm chi nhiều nhất",
    topAccountOutflow: "Ví chi nhiều nhất",
    accountBalances: "Số dư các ví",
    scopeBreakdown: "Nhóm chi lớn",
    categoryBreakdown: "Danh mục chi lớn",
    accountActivity: "Biến động từng ví",
    dailyFlow: "Dòng tiền theo ngày",
  },
  home: {
    pageTitle: "Tổng quan",
    heroMonth: "Tháng này",
    heroTagline: "Theo dõi chi tiêu tháng {{month}}",
    accountsTitle: "Tài khoản",
    accountsSubtitle: "Số dư từng ví",
    monthBarTitle: "Tháng này",
    noAccounts: "Chưa có tài khoản",
    noAccountsBody: "Thêm tài khoản ở tab Chi tiêu để theo dõi số dư.",
    todayTitle: "Hôm nay",
    todaySubtitle: "Các khoản thu và chi trong ngày",
    todayEmpty: "Chưa có thu chi hôm nay",
    todayEmptyBody: "Ghi khoản thu hoặc chi để theo dõi trong ngày.",
    todayIncome: "Thu",
    todayExpense: "Chi",
    momTitle: "So với {{month}}",
    momSubtitle: "So sánh thu, chi và số còn lại.",
    monthSummarySubtitle: "Những điểm nổi bật trong tháng.",
    worthNotingSubtitle: "Gợi ý từ dữ liệu tháng này.",
    recentSubtitle: "Bấm một dòng để sửa nhanh.",
    largestExpense: "Khoản chi lớn nhất",
    allGood: "Mọi thứ đang ổn",
    noNoting: "Chưa có điểm đáng lưu ý trong tháng này.",
    noCategory: "Chưa có dữ liệu danh mục",
    noCategoryBody: "Danh mục chi sẽ hiện khi bạn ghi khoản chi trong tháng.",
    noRecent: "Chưa có giao dịch gần đây",
    noRecentBody: "Thêm khoản chi hoặc thu để bắt đầu theo dõi.",
    noMonthSummary: "Chưa có tóm tắt tháng.",
    kpiBalance: "Tổng số dư",
    kpiIncome: "Thu tháng này",
    kpiExpense: "Chi tháng này",
    kpiNet: "Còn lại",
    kpiDebt: "Tiền cho mượn",
    kpiAccounts: "{{count}} tài khoản",
    momExpense: "Chi tiêu",
    momIncome: "Thu nhập",
    momNet: "Còn lại",
    filterTitle: "Xem theo ví",
    filterSubtitle: "Lọc thu chi hôm nay, tháng này và dòng tiền theo ngày.",
    filterActiveSubtitle: "Đang xem dữ liệu của {{account}}.",
    filterActiveNote: "Đang lọc theo {{account}}",
    filterAll: "Tất cả ví",
    filterNoAccounts: "Thêm tài khoản để lọc theo ví.",
    dailyFlowTitle: "Dòng tiền theo ngày",
    dailyFlowMeta: "Tháng này — ngày có giao dịch, mới nhất lên trên.",
    dailyFlowDayCount: "{{count}} ngày",
    dailyFlowNetLabel: "Ròng",
    dailyFlowEmpty: "Chưa có dòng tiền tháng này",
    dailyFlowEmptyBody: "Ghi thu hoặc chi để theo dõi biến động từng ngày.",
    dailyFlowLoadTitle: "Dòng tiền theo ngày",
    dailyFlowLoadBody: "Bấm để xem biến động từng ngày trong tháng — không tải tự động.",
    dailyFlowLoadAction: "Xem dòng tiền",
    kpiDebtLoadHint: "{{count}} người · tải tab Cho mượn",
    kpiDebtEmpty: "Chưa có người mượn",
    momTitle: "So với tháng trước",
    momMeta: "Chi, thu và còn lại so với tháng liền trước.",
    momLoadMeta: "Tải khi cần — không quét tháng trước tự động.",
    momLoadTitle: "So với tháng trước",
    momLoadBody: "Bấm để so sánh chi, thu và còn lại với tháng liền trước.",
    momLoadAction: "Xem so với tháng trước",
    momCompareNote: "So với {{month}}",
    topCategoriesMeta: "Tháng này — từ cache hiện tại.",
    recentMeta: "7 ngày gần nhất trong tháng này.",
  },
  auth: {
    title: "Hung Tran Finance",
    subtitle: "Tài chính cá nhân",
    loginButton: "Đăng nhập với Google",
  },
  common: {
    guest: "Khách",
    loading: "Đang tải dữ liệu...",
    save: "Lưu",
    cancel: "Hủy",
    close: "Đóng",
    delete: "Xóa",
    edit: "Sửa",
  },
  finance: {
    monthInfo: "Tất cả giao dịch trong tháng {{month}}.",
    workspaceInfo: "Ghi và tìm mọi khoản chi, thu, chuyển.",
    ledgerInfo: "Giao dịch trong kỳ đang xem.",
    subTab: {
      ledger: "Giao dịch",
      manage: "Quản lý",
    },
    manage: {
      accountsTitle: "Tài khoản",
      scopesTitle: "Nhóm chi",
    },
    emptyLedgerTitle: "Chưa có giao dịch nào trong tháng này",
    emptyLedgerBody: "Thêm một khoản chi, khoản thu hoặc chuyển khoản để bắt đầu.",
    monthLoadTitle: "Giao dịch tháng này",
    monthLoadBody: "Bấm tải để xem toàn bộ giao dịch trong tháng — mặc định trang Chi tiêu chỉ hiển thị theo ngày.",
    monthLoadAction: "Tải giao dịch tháng",
    monthLoadWorkspaceInfo: "Chọn Tháng này rồi bấm Tải giao dịch tháng để xem toàn bộ giao dịch trong tháng.",
    monthLoadLedgerInfo: "Đang xem theo ngày. Tải tháng để xem toàn bộ giao dịch trong kỳ.",
    manageEmptyTitle: "Chưa có tài khoản",
    manageEmptyBody: "Tạo tài khoản đầu tiên để ghi thu chi và theo dõi số dư.",
    manageEmptyAction: "Thêm tài khoản đầu tiên",
    emptyAccountsTitle: "Chưa có tài khoản nào",
    emptyAccountsBody: "Tạo ít nhất một tài khoản để bắt đầu theo dõi số dư và ghi nhận giao dịch.",
    filterDrawer: "Bộ lọc",
    filterDrawerHint: "Tài khoản, loại, danh mục...",
    scopePlaceholder: "Ví dụ: Tôi, Gia đình, Thuê nhà",
    scopeSummary: "{{count}} nhóm",
    accountsSyncNote: "Số dư hiện tại được đồng bộ từ giao dịch.",
    scopeHint: "Tách khoản chi theo người hoặc mục đích.",
    composer: {
      createExpense: "Thêm khoản chi",
      createIncome: "Thêm khoản thu",
      createTransfer: "Thêm chuyển khoản",
      createAdjustment: "Sửa số dư",
      editExpense: "Sửa khoản chi",
      editIncome: "Sửa khoản thu",
      editTransfer: "Sửa chuyển khoản",
      editAdjustment: "Sửa số dư",
      expenseHint: "Khoản chi sẽ trừ trực tiếp vào số dư của tài khoản đã chọn.",
      incomeHint: "Khoản thu sẽ cộng trực tiếp vào số dư của tài khoản đã chọn.",
      transferHint: "Chuyển khoản chỉ đổi chỗ tiền giữa hai tài khoản, không tính vào thu hoặc chi.",
      adjustmentHint: "Dùng khi cần chỉnh số dư cho khớp thực tế. Có thể nhập số dương hoặc âm.",
      shortcuts: {
        expense:
          "Phím tắt: C mở form chi nhanh (tab Tổng quan hoặc Chi tiêu) · / tìm trong sổ (tab Chi tiêu)",
        income: "Phím tắt: I mở form thu nhanh (tab Tổng quan hoặc Chi tiêu)",
      },
    },
    account: {
      active: "Đang dùng",
      archived: "Đã lưu trữ",
      default: "Mặc định",
      openingBalance: "Đầu kỳ {{amount}}",
      createTitle: "Thêm tài khoản",
      editTitle: "Sửa tài khoản",
      createHint: "Số dư đầu kỳ chỉ nhập một lần khi tạo tài khoản.",
      editHint: "Cập nhật tên, loại hoặc trạng thái mặc định. Để sửa số dư, dùng Sửa số dư.",
      createAction: "Tạo tài khoản",
      saveChanges: "Lưu thay đổi",
    },
    transactionType: {
      expense: "Khoản chi",
      income: "Khoản thu",
      transfer: "Chuyển khoản",
      adjustment: "Sửa số dư",
    },
    summary: {
      totalBalance: "Tổng số dư",
      income: "Thu trong tháng",
      expense: "Chi trong tháng",
      net: "Còn lại",
      transfer: "Chuyển khoản tháng",
    },
    filter: {
      account: "Tài khoản",
      type: "Loại",
      category: "Danh mục",
      scope: "Nhóm chi",
      allAccounts: "Tất cả tài khoản",
      allTypes: "Tất cả loại",
      allCategories: "Tất cả danh mục",
      allScopes: "Tất cả nhóm",
      pickScope: "Chọn nhóm chi",
      searchPlaceholder: "Tìm ghi chú, tài khoản... (/ để focus)",
    },
    scope: {
      create: "Thêm nhóm",
      renameTitle: "Đổi tên nhóm chi",
      deleteTitle: "Xóa nhóm chi",
      deleteHint: "Chọn nhóm thay thế nếu cần chuyển giao dịch trước khi xóa.",
      renameHint: "Đổi tên nhóm mà không làm mất liên kết với các khoản chi cũ.",
      deleteAction: "Xóa nhóm",
    },
    expenseDetailsInfo: "Xem lại toàn bộ khoản chi trong kỳ đang xem.",
  },
  loans: {
    pageTitle: "Cho mượn",
    workspaceInfo: "Tiền cho bạn bè mượn — tách khỏi chi tiêu hằng ngày.",
    partiesStripHint: "Chọn người để xem và ghi công nợ.",
    spotlightNote: "{{count}} người đang nợ",
    partiesTitle: "Người mượn",
    partiesSubtitle: "Theo dõi tổng đã mượn, đã trả và số còn nợ.",
    historyTitle: "Lịch sử công nợ",
    historyEmpty: "Chưa có lịch sử công nợ",
    historyEmptyBody: "Chọn hoặc thêm người để xem lịch sử.",
    historyEmptyParty: "Người này chưa có giao dịch cho mượn hoặc trả lại.",
    selectedPartyMetaEmpty: "Chọn một người mượn để xem lịch sử công nợ.",
    loadSelectedPartyMeta: "Tải lịch sử để xem chi tiết công nợ của người này.",
    loadTitle: "Lịch sử công nợ",
    loadBody: "Tải giao dịch cho mượn khi cần — tránh quét toàn bộ lịch sử mỗi lần mở app.",
    loadAction: "Tải lịch sử công nợ",
    loadPartyHint: "Tải lịch sử để xem số liệu",
    summaryLoadTitle: "Tóm tắt cho mượn",
    summaryLoadBody: "Bấm tải để xem tổng còn nợ và lịch sử giao dịch.",
    addParty: "Thêm người",
    chipLend: "Cho mượn",
    chipRepay: "Nhận trả",
    chipParty: "Người mượn",
    summary: {
      totalOutstanding: "Tổng còn nợ",
      activePartyCount: "Người đang nợ",
      lentTotal: "Đã cho mượn",
      repaidTotal: "Đã nhận trả",
    },
    party: {
      edit: "Sửa",
      delete: "Xóa",
      settled: "Đã trả hết",
      emptyTitle: "Chưa có người mượn nào",
      emptyBody: "Thêm người mượn đầu tiên để bắt đầu theo dõi công nợ.",
      countSuffix: "người",
      txSuffix: "giao dịch",
    },
    entry: {
      shortcutsLend: "Từ tab Cho mượn: dùng chip Cho mượn để ghi nhanh khoản cho mượn.",
      shortcutsRepay: "Từ tab Cho mượn: dùng chip Nhận trả để ghi nhanh khoản nhận trả.",
      createLend: "Cho mượn",
      createRepay: "Nhận trả",
      editLend: "Sửa cho mượn",
      editRepay: "Sửa nhận trả",
      lendHint: "Khoản này sẽ trừ trực tiếp khỏi số dư tài khoản bạn chọn.",
      repayHint: "Khoản này sẽ tăng lại số dư tài khoản nhận tiền.",
      pickParty: "Chọn người mượn",
      pickAccount: "Chọn tài khoản",
      noNote: "Không có ghi chú",
    },
    partyForm: {
      createTitle: "Thêm người mượn",
      editTitle: "Sửa người mượn",
      hint: "Dùng tên người hoặc nhóm bạn cần theo dõi công nợ riêng.",
    },
  },
  reports: {
    workspaceInfo: "Phân tích chi tiêu theo kỳ bạn chọn.",
    shellTitle: "Báo cáo chi tiết",
    presetCurrentMonth: "Tháng này",
    presetPreviousMonth: "Tháng trước",
    sectionCash: "Số dư hiện tại",
    sectionSignals: "Tóm tắt kỳ",
    sectionAttention: "Điểm đáng lưu ý",
    sectionCategory: "Danh mục chi lớn",
    sectionScope: "Nhóm chi lớn",
    sectionAccounts: "Tài khoản",
    cashSnapshotSubtitle: "{{count}} ví đang dùng",
    periodSummarySubtitle: "Điểm nổi bật trong kỳ đang xem.",
    worthNotingSubtitle: "Gợi ý từ dữ liệu kỳ này.",
    categorySubtitle: "Nhìn theo tỷ trọng chi.",
    scopeSubtitle: "Nhóm nào đang chi nhiều hơn.",
    accountsSubtitle: "Dòng vào, ra và số dư.",
    fromDate: "Từ ngày",
    toDate: "Đến ngày",
    apply: "Áp dụng",
    reset: "Đặt lại",
    breadcrumbHome: "Tổng quan",
    emptySignals: "Chưa có tóm tắt kỳ.",
    emptyAttention: "Chưa có điểm đáng lưu ý.",
    emptyCategory: "Chưa có khoản chi trong kỳ này.",
    emptyScope: "Chưa có nhóm chi trong kỳ này.",
    emptyAccount: "Chưa có biến động tài khoản trong kỳ này.",
    emptyFlow: "Chưa có dòng tiền trong kỳ này.",
    loadTitle: "Báo cáo chi tiết",
    loadBody: "Chọn kỳ rồi bấm Tải báo cáo hoặc Áp dụng — không tải tự động khi mở tab.",
    loadAction: "Tải báo cáo",
    momLoadTitle: "So với kỳ trước",
    momLoadBody: "Bấm để so sánh chi, thu và còn lại với kỳ liền trước.",
    momLoadAction: "So với kỳ trước",
    drillHint: "Bấm một hàng để mở sổ giao dịch đã lọc.",
  },
  toast: {
    signInRequired: "Vui lòng đăng nhập trước.",
    loadFail: "Không thể tải dữ liệu tài chính. Vui lòng thử lại.",
    transactionSaved: "Đã lưu giao dịch.",
    transactionDeleted: "Đã xóa giao dịch.",
    transactionSaveFail: "Không thể lưu giao dịch.",
    transactionDeleteFail: "Không thể xóa giao dịch.",
    accountCreated: "Đã tạo tài khoản mới.",
    accountCreateFail: "Không thể tạo tài khoản.",
    accountUpdated: "Đã cập nhật tài khoản.",
    accountUpdateFail: "Không thể cập nhật tài khoản.",
    accountNotFound: "Không tìm thấy tài khoản.",
    accountRemoved: "Đã cập nhật trạng thái tài khoản.",
    accountRemoveFail: "Không thể cập nhật tài khoản.",
    financeResetDone: "Đã xóa sạch dữ liệu tài chính cũ.",
    financeResetFail: "Không thể xóa dữ liệu tài chính.",
    csvExportSuccess: "Đã xuất CSV theo bộ lọc hiện tại.",
    csvExportFail: "Không thể xuất CSV.",
    reportLoadFail: "Không thể tải báo cáo tài chính.",
    scopeCreated: "Đã thêm nhóm chi mới.",
    scopeCreateFail: "Không thể thêm nhóm chi.",
    scopeNotFound: "Không tìm thấy nhóm chi cần xóa.",
    scopePickRequired: "Vui lòng chọn nhóm chi.",
  },
};

export function t(path, fallback = "") {
  if (!path) return fallback;

  const chunks = String(path).split(".");
  let cursor = copyVi;

  for (const key of chunks) {
    if (!cursor || !Object.prototype.hasOwnProperty.call(cursor, key)) return fallback;
    cursor = cursor[key];
  }

  return cursor ?? fallback;
}

export function formatTemplate(template, payload = {}) {
  let output = String(template || "");
  Object.entries(payload).forEach(([key, value]) => {
    output = output.replaceAll(`{{${key}}}`, String(value ?? ""));
  });
  return output;
}
