export const copyVi = {
  brand: {
    name: "NEXUS OS",
    subtitle: "Không gian làm việc cá nhân của Hưng Trần",
    owner: "Hưng Trần",
  },
  nav: {
    dashboard: "Trung tâm",
    expenses: "Chi tiêu",
    goals: "Mục tiêu",
    videoPlan: "Kế hoạch video",
    classes: "Lớp học",
    weeklyReview: "Tổng kết tuần",
    accounts: "Tài khoản",
    settings: "Cài đặt",
  },
  routeMeta: {
    auth: {
      title: "Xin chào Hưng Trần",
      subtitle: "Đăng nhập để tiếp tục",
    },
    dashboard: {
      title: "Trung tâm",
      subtitle: "Ưu tiên video, mục tiêu và tài chính mỗi ngày",
    },
    expenses: {
      title: "Chi tiêu",
      subtitle: "Theo dõi và tối ưu dòng tiền",
    },
    goals: {
      title: "Mục tiêu & Động lực",
      subtitle: "Duy trì tiến độ mỗi ngày",
    },
    "video-plan": {
      title: "Kế hoạch video",
      subtitle: "Điều phối workflow YouTube 6 bước",
    },
    classes: {
      title: "Lớp học",
      subtitle: "Quản lý lớp, học sinh và 14 buổi học cố định",
    },
    "weekly-review": {
      title: "Tổng kết tuần",
      subtitle: "Nhìn lại tuần cũ và chuẩn bị lịch phát hành",
    },
    accounts: {
      title: "Tài khoản",
      subtitle: "Quản lý số dư và luồng tiền",
    },
    settings: {
      title: "Cài đặt",
      subtitle: "Hồ sơ và tùy chọn cá nhân",
    },
  },
  common: {
    guest: "Khách",
    month: "Tháng",
    loading: "Đang tải dữ liệu...",
    noData: "Chưa có dữ liệu",
    allAccounts: "Tất cả tài khoản",
    save: "Lưu",
    cancel: "Hủy",
    delete: "Xóa",
    edit: "Sửa",
    close: "Đóng",
    apply: "Áp dụng",
    reset: "Đặt lại",
  },
  cta: {
    addExpense: "+ Thêm khoản chi",
    addGoal: "Mở mục tiêu hôm nay",
    addVideoTask: "Thêm công việc video",
    weeklyReview: "Tổng kết tuần",
    openVideoBoard: "Mở bảng video",
    checkIn: "Điểm danh",
  },
  dashboard: {
    hero: {
      greeting: {
        morning: "Chào buổi sáng, {{name}}",
        afternoon: "Chào buổi chiều, {{name}}",
        evening: "Chào buổi tối, {{name}}",
      },
      missionTitle: "Nhiệm vụ hôm nay",
      missionDefault: "Hoàn thành 1 mục tiêu và đẩy 1 công việc video tiến lên trong hôm nay.",
      missionHabit: "Bạn còn {{count}} lượt thói quen cần hoàn thành trong kỳ hiện tại.",
      missionVideo: "Bạn còn {{count}} công việc video chưa xuất bản. Ưu tiên đẩy sang bước kế tiếp.",
      quickActionsTitle: "Hành động nhanh",
      meta: "Trạng thái theo thời gian thực của tháng đang chọn",
    },
    priority: {
      title: "Ưu tiên hôm nay",
      empty: "Không có việc gấp cần xử lý ngay.",
      habitMeta: "{{done}}/{{target}} lượt • {{period}}",
      videoMetaNoDue: "Video chưa có hạn • {{stage}}",
      videoMetaDue: "Hạn {{dueDate}} • {{stage}}",
      actionCheckIn: "Điểm danh",
      actionOpenVideo: "Mở bảng video",
    },
    actionBoard: {
      title: "Bảng hành động hôm nay",
      subtitle: "Tập trung vào việc kế tiếp và các công việc video cận hạn {{hours}} giờ.",
      nextTitle: "Việc kế tiếp",
      deadlineTitle: "Cận hạn {{hours}} giờ",
      summaryTitle: "Tóm tắt hành động",
      emptyNext: "Không còn việc ưu tiên cần xử lý ngay.",
      emptyDeadline: "Không có công việc video cận hạn trong {{hours}} giờ tới.",
      summary: "Hôm nay còn {{habitCount}} lượt thói quen và {{videoCount}} công việc video mở.",
      summaryDone: "Hôm nay không có việc khẩn cấp.",
      quickCheckin: "Điểm danh ngay",
      quickOpenDeadline: "Mở việc cận hạn",
    },
    nextAction: {
      habitBadge: "Thói quen",
      videoBadge: "Video",
      actionCheckIn: "Điểm danh",
      actionOpenVideo: "Mở công việc",
      actionOpenBoard: "Mở bảng",
      habitMeta: "{{remaining}} lượt còn lại • {{period}}",
      videoMetaDue: "Hạn {{dueDate}} • {{stage}}",
      videoMetaNoDue: "Chưa có hạn • {{stage}}",
    },
    deadline: {
      dueLabel: "Hạn {{dueDate}}",
      stageLabel: "Giai đoạn: {{stage}}",
    },
    reminder: {
      overdue: "Quá hạn {{count}}",
      today: "Hôm nay {{count}}",
      soon: "Cận hạn {{hours}}h {{count}}",
      overdueLabel: "Quá hạn",
      todayLabel: "Hôm nay",
      soonLabel: "Cận hạn",
    },
    modules: {
      video: {
        title: "Luồng video tuần này",
        subtitle: "Ưu tiên xử lý các công việc sắp tới hạn.",
        link: "Mở bảng",
      },
      goals: {
        title: "Mục tiêu đang chạy",
        subtitle: "Theo dõi tiến độ và hoàn thành mục tiêu trọng tâm.",
        link: "Mở chi tiết",
      },
      motivation: {
        title: "Động lực",
        subtitle: "Thử thách ngày/tuần/tháng + XP + cấp độ.",
        link: "Xem thử thách",
      },
      accounts: {
        title: "Số dư tài khoản",
        empty: "Chưa có dữ liệu số dư tài khoản.",
      },
    },
    classes: {
      title: "Buổi học sắp tới",
      empty: "Chưa có buổi học nào sắp tới.",
      open: "Mở lớp học",
    },
    heroKpi: {
      videoOpen: "Việc video đang mở",
      habitLeft: "Lượt thói quen còn lại",
      activeGoals: "Mục tiêu đang chạy",
    },
  },
  goals: {
    status: {
      done: "Hoàn thành",
      active: "Đang chạy",
      reached: "Đã đạt",
    },
    table: {
      emptyGoals: "Chưa có mục tiêu nào.",
      emptyHabits: "Chưa có thói quen nào.",
    },
    dailyFocus: {
      title: "Hôm nay cần làm gì",
      subtitle: "Ưu tiên các thói quen còn thiếu quota để giữ tiến độ tuần.",
      empty: "Tuyệt vời! Bạn đã hoàn thành toàn bộ quota kỳ hiện tại.",
      action: "Điểm danh nhanh",
      remaining: "Còn {{remaining}} lượt",
    },
  },
  videoPlan: {
    layout: {
      pageTitle: "Kế hoạch video YouTube",
      pageSubtitle: "Vận hành lịch sản xuất nội dung theo 6 giai đoạn rõ ràng và dễ theo dõi.",
      createTitle: "Tạo nhanh công việc video",
      createSubtitle: "Điền thông tin cốt lõi, sau đó dùng AI/template để hoàn thiện nội dung.",
      filtersTitle: "Bộ lọc và điều hướng",
      filtersSubtitle: "Lọc theo giai đoạn, ưu tiên, trạng thái kết quả và từ khóa.",
      viewModeLabel: "Chế độ hiển thị",
      calendarTitle: "Lịch sản xuất",
      agendaTitle: "Lịch theo ngày",
      unscheduledTitle: "Chưa lên lịch",
      openBoard: "Mở bảng video",
    },
    filters: {
      title: "Bộ lọc bảng",
      stageAll: "Tất cả giai đoạn",
      priorityAll: "Tất cả ưu tiên",
      queryPlaceholder: "Tìm theo tiêu đề hoặc ghi chú...",
      reset: "Đặt lại",
      summary: "{{filtered}}/{{total}} công việc đang hiển thị",
    },
    form: {
      addTitle: "Tạo công việc video mới",
      editTitle: "Chỉnh sửa công việc video",
      noDeadline: "Không hạn",
      deadlineLabel: "Hạn",
      stageLabel: "Giai đoạn",
      noNote: "Không có ghi chú",
      emptyBoard: "Chưa có công việc phù hợp bộ lọc.",
      emptySummary: "Chưa có công việc video.",
      editAction: "Sửa nhanh",
      deleteAction: "Xóa",
    },
    stage: {
      idea: "Ý tưởng",
      research: "Nghiên cứu",
      script: "Kịch bản",
      shoot: "Quay",
      edit: "Dựng",
      publish: "Xuất bản",
    },
    priority: {
      low: "Thấp",
      medium: "Vừa",
      high: "Cao",
    },
    calendar: {
      monthFallback: "Tháng hiện tại",
      selectedDate: "Lịch ngày {{date}}",
      selectedDateFallback: "Lịch theo ngày",
      count: "{{count}} việc",
      overdueCount: "Quá hạn {{count}}",
      openTask: "Mở công việc",
      empty: "Chưa có lịch video cho tháng đang chọn.",
      emptyDay: "Ngày này chưa có công việc video.",
      emptyUnscheduled: "Không có công việc chưa lên lịch.",
    },
    reminder: {
      overdue: "Quá hạn: {{count}}",
      today: "Hôm nay: {{count}}",
      soon: "Cận hạn {{hours}}h: {{count}}",
    },
    retro: {
      title: "Kết quả xuất bản",
      doneBadge: "Đã ghi kết quả",
      missingBadge: "Chưa ghi kết quả",
      openButton: "Kết quả xuất bản",
      saveButton: "Lưu kết quả",
      empty: "Chưa có dữ liệu hậu xuất bản cho video này.",
      filterLabel: "Trạng thái kết quả",
      filterAll: "Tất cả",
      filterWith: "Đã ghi kết quả",
      filterWithout: "Chưa ghi kết quả",
      publishedAt: "Ngày xuất bản",
      duration: "Thời lượng (giây)",
      views: "Lượt xem",
      ctr: "CTR (%)",
      retention30s: "Retention 30s (%)",
      note: "Ghi chú rút kinh nghiệm",
    },
    blueprints: {
      title: "Mẫu nội dung",
      filterLanguage: "Ngôn ngữ",
      filterVideoType: "Định dạng",
      placeholder: "Chọn mẫu nội dung",
      applyButton: "Áp dụng template",
      saveButton: "Lưu thành template",
      fallbackName: "Mẫu nội dung AI",
      short: "Video ngắn 30s",
      long: "Video dài 5-10 phút",
      noData: "Chưa có template phù hợp. Hãy tạo từ AI gợi ý đầu tiên.",
    },
  },
  ai: {
    common: {
      apply: "Áp dụng toàn bộ",
      cooldown: "Thử lại sau {{sec}}s",
      cooldownToast: "Vui lòng chờ {{sec}} giây trước khi gọi AI tiếp theo.",
    },
    expenseLabel: {
      suggested: "AI đề xuất danh mục {{category}} (độ tin cậy {{confidence}}).",
      autoApplied: "AI đã tự gán danh mục {{category}} ({{confidence}}).",
      manualApplied: "Đã áp dụng danh mục {{category}} từ gợi ý AI.",
      errorHint: "Chưa thể gợi ý danh mục lúc này. Bạn vẫn có thể chọn thủ công.",
    },
    videoCopilot: {
      generate: "AI gợi ý mới",
      improve: "AI cải thiện nội dung",
      generateLoading: "Đang tạo gợi ý...",
      improveLoading: "Đang cải thiện...",
      empty: "Bấm AI gợi ý để nhận phương án video theo ngữ cảnh hiện tại.",
      optionUntitled: "Phương án chưa có tiêu đề",
      optionIndex: "Ph\u01b0\u01a1ng \u00e1n {{index}}",
      deadline: "Hạn gợi ý",
      noDeadline: "Không có hạn gợi ý",
      reasonLabel: "L\u00fd do g\u1ee3i \u00fd",
      shotListLabel: "Danh s\u00e1ch c\u1ea3nh quay",
      noteLabel: "Ghi ch\u00fa tri\u1ec3n khai",
      hookLabel: "Hook mở đầu",
      outlineLabel: "Dàn ý triển khai",
      ctaLabel: "Kêu gọi hành động",
      videoTypeLabel: "Định dạng video",
      saveTemplate: "Lưu thành template",
    },
    goalCopilot: {
      generate: "AI gợi ý mới",
      improve: "AI cải thiện nội dung",
      generateLoading: "Đang tạo gợi ý...",
      improveLoading: "Đang cải thiện...",
      empty: "Bấm AI gợi ý để nhận bundle mục tiêu và thói quen phù hợp.",
      optionUntitled: "Mục tiêu chưa có tên",
      habitUntitled: "Thói quen chưa có tên",
      habitLabel: "Thói quen đi kèm",
    },
  },
  weeklyReview: {
    header: {
      title: "Tổng kết tuần",
      subtitle: "Nghi thức review cuối tuần để ra quyết định nhanh cho tuần mới.",
      weekLabel: "Tuần {{weekKey}} • {{range}}",
      fallbackWeek: "Tuần hiện tại",
    },
    cards: {
      finance: "Tài chính tuần",
      goals: "Mục tiêu & thói quen",
      video: "Video tuần này",
      videoPerformance: "Hiệu suất video tuần",
      motivation: "Động lực tuần",
    },
    finance: {
      income: "Tổng thu",
      expense: "Tổng chi",
      net: "Dòng tiền ròng",
      transfer: "Chuyển khoản nội bộ",
      transactions: "Số giao dịch",
    },
    goals: {
      active: "Mục tiêu đang chạy",
      done: "Mục tiêu đã hoàn thành",
      habitsTotal: "Thói quen đang theo dõi",
      habitsReached: "Thói quen đạt quota",
      checkins: "Lượt điểm danh",
    },
    video: {
      open: "Công việc đang mở",
      done: "Công việc đã xong",
      dueWeek: "Công việc có hạn trong tuần",
      dueWindow: "Công việc cận hạn {{hours}}h",
      overdue: "Công việc quá hạn",
    },
    videoPerformance: {
      published: "Video đã xuất bản",
      totalViews: "Tổng lượt xem",
      avgCtr: "CTR trung bình",
      avgRetention30s: "Retention 30s",
      avgDuration: "Thời lượng trung bình",
      noData: "Chưa có dữ liệu hiệu suất tuần này.",
      insightTitle: "Gợi ý cải thiện tuần mới",
      lowCtr: "CTR đang thấp, ưu tiên tối ưu tiêu đề và hook mở đầu.",
      lowRetention: "Retention 30s thấp, rút gọn mở đầu và vào nội dung chính sớm hơn.",
      lowPublish: "Số video xuất bản còn thấp, cần chốt deadline và giữ nhịp đăng đều.",
      healthy: "Hiệu suất tuần ổn định, tiếp tục giữ nhịp và tăng độ khó từng chủ đề.",
    },
    motivation: {
      streak: "Chuỗi ngày",
      totalXp: "Tổng XP",
      level: "Cấp độ",
      weekXp: "XP trong tuần",
      challengeWeek: "Thử thách tuần",
    },
    plan: {
      title: "Kế hoạch tuần mới",
      focusTheme: "Chủ đề trọng tâm",
      priority1: "Ưu tiên 1",
      priority2: "Ưu tiên 2",
      priority3: "Ưu tiên 3",
      riskNote: "Rủi ro cần lưu ý",
      actionCommitments: "Cam kết hành động",
      save: "Lưu tổng kết tuần",
    },
    history: {
      title: "Lịch sử review gần đây",
      empty: "Chưa có lịch sử tổng kết tuần.",
      hasPlan: "Đã có kế hoạch",
      noPlan: "Chưa có kế hoạch",
    },
    status: {
      idle: "Sẵn sàng tổng kết tuần",
      saving: "Đang lưu...",
      saved: "Đã lưu",
      savedAt: "Đã lưu lúc {{time}}",
      error: "Lưu thất bại",
    },
    weekly: {
      saving: "Đang lưu kế hoạch tuần...",
      savedAt: "Đã lưu lúc {{time}}",
      saved: "Đã lưu kế hoạch tuần",
      error: "Lưu mục tiêu tuần thất bại",
      ready: "Sẵn sàng cập nhật mục tiêu tuần",
      currentWeek: "Tuần hiện tại",
      label: "Kế hoạch tuần {{weekKey}}",
      unsaved: "Bạn đang có thay đổi chưa lưu cho mục tiêu tuần",
    },
  },
  classes: {
    title: "Quản lý lớp học",
    subtitle: "Theo dõi lịch 14 buổi, học sinh và ghi chú từng buổi.",
    listTitle: "Danh sách lớp",
    detailTitle: "Chi tiết lớp",
    studentsTitle: "Học sinh",
    sessionsTitle: "Lịch 14 buổi",
    sessionEditorTitle: "Ghi chú buổi học",
    reviewTableTitle: "Nhận xét từng học sinh",
    formModeCreate: "Tạo lớp mới",
    formModeEdit: "Đang sửa lớp đã chọn",
    formModeRead: "Đang xem lớp đã hoàn thành",
    emptyClasses: "Chưa có lớp học nào. Hãy tạo lớp đầu tiên.",
    emptyCompleted: "Chưa có lớp nào hoàn thành.",
    emptyClassDetail: "Chọn một lớp để xem chi tiết.",
    emptyStudents: "Chưa có học sinh. Hãy thêm học sinh cho lớp.",
    emptySessions: "Chưa có lịch 14 buổi. Hãy lưu lớp để tự sinh lịch.",
    emptySessionEditor: "Chọn buổi học để nhập kế hoạch và nhận xét.",
    emptyStudentsForSession: "Chưa có học sinh áp dụng cho buổi này.",
    emptySlots: "Chưa có lịch cố định",
    untitledClass: "Lớp chưa đặt tên",
    noUpcomingSession: "Chưa có buổi sắp tới",
    noRecentSession: "Chưa có buổi đã dạy",
    readOnly: "Chỉ xem",
    progressLabel: "Đã dạy {{progress}} • Còn {{remaining}} buổi",
    sessionRescheduledFrom: "Đã dời từ {{date}}",
    confirmDelete: "Bạn chắc chắn muốn xóa lớp học này?",
    selectClassFirst: "Vui lòng chọn lớp trước khi thêm học sinh.",
    tabs: {
      active: "Đang dạy",
      completed: "Đã hoàn thành",
    },
    badges: {
      completed: "Hoàn thành",
    },
    labels: {
      session: "Buổi",
      startDate: "Bắt đầu",
      schedule: "Lịch học",
      duration: "Mỗi buổi",
      minute: "phút",
      upcoming: "Buổi sắp tới",
      recent: "Buổi gần nhất",
    },
    student: {
      active: "Đang học",
      inactive: "Tạm ngừng",
      table: {
        name: "Học sinh",
        status: "Trạng thái",
        scope: "Mốc áp dụng",
        actions: "Thao tác",
      },
    },
    actions: {
      selectClass: "Chọn lớp",
      addClass: "Tạo lớp",
      saveClass: "Lưu lớp",
      deleteClass: "Xóa lớp",
      resetForm: "Tạo mới",
      addStudent: "Thêm học sinh",
      removeStudent: "Ngừng từ buổi kế",
      reactivateStudent: "Kích hoạt lại",
      reopenClass: "Mở lại lớp",
      shiftSessionNextWeek: "Dời sang tuần kế",
      saveSessionReview: "Lưu ghi chú buổi",
    },
    review: {
      notePlaceholder: "Ghi chú ngắn",
      table: {
        status: "Đánh giá",
        note: "Ghi chú",
      },
    },
  },
  settings: {
    tabs: {
      profile: "Hồ sơ cá nhân",
      dashboard: "Tùy chọn Dashboard",
      filters: "Bộ lọc & Hiển thị",
    },
    profile: {
      title: "Hồ sơ cá nhân",
      subtitle: "Thông tin này ảnh hưởng trực tiếp đến dashboard cá nhân hóa.",
      displayName: "Tên hiển thị",
      displayNamePlaceholder: "Ví dụ: Hưng Trần",
      tagline: "Tagline",
      taglinePlaceholder: "Ví dụ: Tập trung tăng trưởng nội dung đều mỗi tuần",
      missionDefault: "Nhiệm vụ mặc định",
      missionDefaultPlaceholder: "Ví dụ: Hoàn thành 1 bước video và 1 hành động tài chính",
    },
    preferences: {
      dashboard: {
        title: "Tùy chọn Dashboard",
        nextActionsMax: "Số việc kế tiếp hiển thị",
        deadlineWindowHours: "Khung giờ cảnh báo cận hạn",
        startRoute: "Route mặc định sau đăng nhập",
        startRouteOptions: {
          dashboard: "Trung tâm",
          goals: "Mục tiêu",
          videoPlan: "Kế hoạch video",
          classes: "Lớp học",
        },
      },
      filters: {
        title: "Bộ lọc & Hiển thị",
        monthMode: "Chế độ tháng mặc định",
        monthModeOptions: {
          current: "Luôn về tháng hiện tại",
          lastUsed: "Nhớ tháng đã dùng gần nhất",
        },
        rememberExpenseFilters: "Nhớ bộ lọc Chi tiêu",
        rememberIncomeFilters: "Nhớ bộ lọc Thu nhập",
        rememberVideoFilters: "Nhớ bộ lọc Video",
      },
      ui: {
        density: "Mật độ giao diện",
        densityOptions: {
          comfortable: "Thoải mái",
          compact: "Gọn",
        },
      },
    },
    status: {
      saving: "Đang lưu...",
      saved: "Đã lưu",
      savedAt: "Đã lưu lúc {{time}}",
      error: "Lưu thất bại",
      idle: "Thay đổi sẽ tự động lưu",
    },
    toast: {
      saveSuccess: "Đã lưu cài đặt.",
      saveFail: "Không thể lưu cài đặt. Hệ thống sẽ thử lại ở lần thay đổi tiếp theo.",
    },
  },
  accounts: {
    transfer: "Chuyển tiền",
    addIncome: "Thêm thu nhập",
    addAccount: "Thêm tài khoản",
    validation: {
      nameRequired: "Vui lòng nhập tên tài khoản",
      nameDuplicate: "Tên tài khoản đã tồn tại",
      idMissing: "Thiếu ID tài khoản",
      nameEmpty: "Tên tài khoản không được để trống",
      deleteIdMissing: "Thiếu ID tài khoản cần xóa",
      reassignRequired: "Vui lòng chọn tài khoản để chuyển dữ liệu",
      transferAccountsRequired: "Vui lòng chọn đầy đủ tài khoản",
      transferAccountDifferent: "Tài khoản chuyển và nhận phải khác nhau",
      transferAmountRequired: "Vui lòng nhập số tiền",
      transferAmountInvalid: "Số tiền không hợp lệ",
      transferDateRequired: "Vui lòng chọn ngày",
    },
    toast: {
      addSuccess: "Đã thêm tài khoản mới",
      addFail: "Không thể thêm tài khoản",
      updateSuccess: "Đã cập nhật tài khoản",
      updateFail: "Không thể cập nhật tài khoản",
      deleteSuccess: "Đã xóa tài khoản",
      deleteFail: "Không thể xóa tài khoản",
      transferSuccess: "Đã chuyển tiền giữa các tài khoản",
      transferFail: "Không thể chuyển tiền",
    },
  },
  emptyState: {
    goals: "Chưa có mục tiêu đang chạy.",
    motivation: "Chưa có dữ liệu động lực.",
    video: "Chưa có công việc video.",
  },
  toast: {
    signInRequired: "Vui lòng đăng nhập trước",
    loadFail: "Không thể tải dữ liệu. Vui lòng thử lại.",
    deleteDataFail: "Không thể xóa dữ liệu",
    expenseAdded: "Đã thêm khoản chi.",
    expenseUpdated: "Đã cập nhật khoản chi.",
    expenseDeleted: "Đã xóa khoản chi.",
    expenseCreateFail: "Không thể thêm khoản chi",
    expenseUpdateFail: "Không thể cập nhật khoản chi",
    expenseNotFound: "Không tìm thấy khoản chi",
    expenseOpenFail: "Không thể mở khoản chi",
    incomeAdded: "Đã thêm khoản thu.",
    incomeUpdated: "Đã cập nhật khoản thu.",
    incomeDeleted: "Đã xóa khoản thu.",
    incomeCreateFail: "Không thể thêm khoản thu",
    incomeUpdateFail: "Không thể cập nhật khoản thu",
    incomeNotFound: "Không tìm thấy khoản thu",
    incomeOpenFail: "Không thể mở khoản thu",
    csvExportFail: "Xuất CSV thất bại.",
    csvExportSuccess: "Đã xuất CSV tháng hiện tại.",
    goalAdded: "Đã tạo mục tiêu mới.",
    goalCreateFail: "Không thể tạo mục tiêu",
    goalProgressUpdated: "Đã cập nhật tiến độ mục tiêu.",
    goalDoneXp: "Đã hoàn thành mục tiêu. +120 XP",
    goalDeleted: "Đã xóa mục tiêu.",
    goalUpdateFail: "Không thể cập nhật mục tiêu",
    habitAdded: "Đã tạo thói quen mới.",
    habitCreateFail: "Không thể tạo thói quen",
    habitNotFound: "Không tìm thấy thói quen",
    habitLocked: "Bạn đã đạt mục tiêu kỳ này",
    habitChecked: "Điểm danh thành công. +{{xp}} XP",
    habitDeleted: "Đã xóa thói quen.",
    habitUpdateFail: "Không thể cập nhật thói quen",
    videoAdded: "Đã thêm công việc video mới.",
    videoUpdated: "Đã cập nhật công việc video.",
    videoNotFound: "Không tìm thấy công việc video",
    videoDeleted: "Đã xóa công việc video.",
    videoCreateFail: "Không thể tạo công việc video",
    videoUpdateFail: "Không thể cập nhật công việc video",
    videoDeleteFail: "Không thể xóa công việc video",
    videoMoved: "Đã chuyển bước công việc video.",
    videoMoveFail: "Không thể chuyển bước",
    videoFilterSaved: "Đã cập nhật bộ lọc video.",
    videoAiReady: "AI đã tạo 3 phương án video.",
    videoAiFallback:
      "AI đang dùng mẫu gợi ý cục bộ. Bạn vẫn có thể bấm tạo lại để lấy phương án mới.",
    videoAiFail: "Không thể tạo gợi ý video lúc này.",
    videoAiApplied: "Đã áp dụng phương án AI vào form video.",
    videoRetroSaved: "Đã lưu kết quả xuất bản.",
    videoRetroSaveFail: "Không thể lưu kết quả xuất bản.",
    videoRetroOpenFail: "Không thể mở dữ liệu kết quả xuất bản.",
    blueprintSaved: "Đã lưu template nội dung.",
    blueprintSaveFail: "Không thể lưu template nội dung.",
    blueprintApplied: "Đã áp dụng template vào form video.",
    blueprintApplyFail: "Không thể áp dụng template đã chọn.",
    goalAiReady: "AI đã tạo 3 bundle mục tiêu.",
    goalAiFail: "Không thể tạo gợi ý mục tiêu lúc này.",
    goalAiApplied: "Đã áp dụng bundle AI vào form mục tiêu.",
    weeklyReviewSaved: "Đã lưu tổng kết tuần.",
    weeklyReviewSaveFail: "Không thể lưu tổng kết tuần.",
    classAdded: "Đã tạo lớp mới.",
    classCreateFail: "Không thể tạo lớp học",
    classUpdated: "Đã cập nhật lớp học.",
    classUpdateFail: "Không thể cập nhật lớp học",
    classDeleted: "Đã xóa lớp học.",
    classDeleteFail: "Không thể xóa lớp học",
    classStudentAdded: "Đã thêm học sinh vào lớp.",
    classStudentAddFail: "Không thể thêm học sinh",
    classStudentRemoved: "Đã cập nhật trạng thái học sinh từ buổi kế.",
    classStudentReactivated: "Đã kích hoạt lại học sinh từ buổi kế.",
    classStudentUpdateFail: "Không thể cập nhật học sinh",
    classSessionSaved: "Đã lưu ghi chú và nhận xét buổi học.",
    classSessionSaveFail: "Không thể lưu buổi học",
    classReopened: "Đã mở lại lớp học.",
    classReopenFail: "Không thể mở lại lớp học",
    classSessionShifted: "Đã dời buổi học và cập nhật lịch chuỗi kế tiếp.",
    classSessionShiftFail: "Không thể dời buổi học",
  },
};

copyVi.classes = {
  ...(copyVi.classes || {}),
  title: "Lớp học",
  subtitle: "Quản lý lớp, học sinh và lịch 14 buổi gọn trong một màn hình.",
  listTitle: "Danh sách lớp",
  detailTitle: "Chi tiết lớp",
  studentsTitle: "Học sinh",
  sessionsTitle: "Lịch 14 buổi",
  sessionEditorTitle: "Ghi chú buổi học",
  reviewTableTitle: "Nhận xét từng học sinh",
  formModeCreate: "Tạo lớp mới",
  formModeEdit: "Đang sửa lớp đã chọn",
  formModeRead: "Đang xem lớp đã hoàn thành",
  emptyClasses: "Chưa có lớp học nào. Hãy tạo lớp đầu tiên.",
  emptyCompleted: "Chưa có lớp nào hoàn thành.",
  emptyClassDetail: "Chọn một lớp để xem chi tiết.",
  emptyStudents: "Chưa có học sinh. Hãy thêm học sinh cho lớp.",
  emptySessions: "Chưa có lịch 14 buổi. Hãy lưu lớp để tự sinh lịch.",
  emptySessionEditor: "Chọn buổi học để nhập ghi chú.",
  emptyStudentsForSession: "Chưa có học sinh áp dụng cho buổi này.",
  emptySlots: "Chưa có lịch cố định",
  untitledClass: "Lớp chưa đặt tên",
  noUpcomingSession: "Chưa có buổi sắp tới",
  noRecentSession: "Chưa có buổi đã dạy",
  readOnly: "Chỉ xem",
  progressLabel: "Đã dạy {{progress}} • Còn {{remaining}} buổi",
  sessionRescheduledFrom: "Đã dời từ {{date}}",
  confirmDelete: "Bạn chắc chắn muốn xóa lớp học này?",
  selectClassFirst: "Vui lòng chọn lớp trước khi thêm học sinh.",
  modes: {
    admin: "Quản trị",
    presentation: "Trình chiếu",
    ...(copyVi.classes?.modes || {}),
  },
  tabs: {
    active: "Đang dạy",
    completed: "Đã hoàn thành",
    ...(copyVi.classes?.tabs || {}),
  },
  badges: {
    completed: "Hoàn thành",
    ...(copyVi.classes?.badges || {}),
  },
  labels: {
    session: "Buổi",
    startDate: "Bắt đầu",
    schedule: "Lịch học",
    duration: "Mỗi buổi",
    minute: "phút",
    upcoming: "Buổi sắp tới",
    recent: "Buổi gần nhất",
    ...(copyVi.classes?.labels || {}),
  },
  score: {
    points: "điểm",
    stars: "sao",
    redeemRatio: "5⭐ = +1 điểm",
    ...(copyVi.classes?.score || {}),
  },
  presentation: {
    title: "Trình chiếu theo lớp",
    titleWithClass: "Trình chiếu lớp: {{name}}",
    subtitle: "Chỉ hiển thị phần cần dùng trong lúc dạy.",
    emptyClasses: "Chưa có lớp đang dạy để trình chiếu.",
    emptyStudents: "Lớp chưa có học sinh đang học.",
    remainLabel: "Còn {{count}} buổi",
    pickPercentLabel: "Xác suất gọi tên: {{percent}}%",
    ...(copyVi.classes?.presentation || {}),
  },
  random: {
    pickButton: "Random tên",
    resultTitle: "Kết quả vừa chọn",
    resultEmpty: "Chưa random lần nào.",
    historyTitle: "5 lượt gần nhất",
    historyEmpty: "Chưa có lịch sử random.",
    normalizedWarning: "Tổng % hiện tại là {{total}}. Hệ thống đang chuẩn hóa theo tổng hiện tại.",
    ...(copyVi.classes?.random || {}),
  },
  student: {
    ...(copyVi.classes?.student || {}),
    active: "Đang học",
    inactive: "Tạm ngưng",
    table: {
      ...(copyVi.classes?.student?.table || {}),
      name: "Học sinh",
      status: "Trạng thái",
      scope: "Mốc áp dụng",
      points: "Điểm",
      stars: "Sao",
      pickPercent: "% random",
      actions: "Thao tác",
    },
  },
  review: {
    notePlaceholder: "Ghi chú ngắn",
    table: {
      status: "Đánh giá",
      note: "Ghi chú",
      ...(copyVi.classes?.review?.table || {}),
    },
    ...(copyVi.classes?.review || {}),
  },
  actions: {
    ...(copyVi.classes?.actions || {}),
    selectClass: "Chọn lớp",
    addClass: "Tạo lớp",
    saveClass: "Lưu lớp",
    deleteClass: "Xóa lớp",
    resetForm: "Tạo mới",
    addStudent: "Thêm học sinh",
    removeStudent: "Ngưng từ buổi kế",
    reactivateStudent: "Kích hoạt lại",
    reopenClass: "Mở lại lớp",
    shiftSessionNextWeek: "Dời sang tuần kế",
    saveSessionReview: "Lưu ghi chú buổi",
    awardStar: "+⭐",
    redeemStars: "Đã sử dụng",
  },
};

copyVi.goals = {
  ...(copyVi.goals || {}),
  weekly: {
    saving: "Đang lưu kế hoạch tuần...",
    savedAt: "Đã lưu lúc {{time}}",
    saved: "Đã lưu kế hoạch tuần",
    error: "Lưu mục tiêu tuần thất bại",
    ready: "Sẵn sàng cập nhật mục tiêu tuần",
    currentWeek: "Tuần hiện tại",
    label: "Kế hoạch tuần {{weekKey}}",
    unsaved: "Bạn đang có thay đổi chưa lưu cho mục tiêu tuần",
    ...((copyVi.goals && copyVi.goals.weekly) || {}),
  },
};

copyVi.weeklyReview = {
  ...(copyVi.weeklyReview || {}),
  filters: {
    modeLabel: "Bộ lọc",
    byWeek: "Theo tuần",
    byMonth: "Theo tháng",
    weekLabel: "Tuần",
    monthLabel: "Tháng",
    ...((copyVi.weeklyReview && copyVi.weeklyReview.filters) || {}),
  },
  cards: {
    actions: "Hành động ưu tiên",
    ...((copyVi.weeklyReview && copyVi.weeklyReview.cards) || {}),
  },
  video: {
    dueMonth: "Công việc có hạn trong tháng",
    ...((copyVi.weeklyReview && copyVi.weeklyReview.video) || {}),
  },
  history: {
    hiddenForMonth: "Lịch sử review chỉ hiển thị ở chế độ tuần.",
    ...((copyVi.weeklyReview && copyVi.weeklyReview.history) || {}),
  },
};

copyVi.dashboard = {
  ...(copyVi.dashboard || {}),
  classes: {
    ...((copyVi.dashboard && copyVi.dashboard.classes) || {}),
    title: "Buổi học sắp tới",
    empty: "Chưa có buổi học nào sắp tới.",
    open: "Vào lớp học",
  },
};

copyVi.toast = {
  ...(copyVi.toast || {}),
  classStarAwarded: "Đã cộng 1⭐ cho học sinh.",
  classStarAwardFail: "Không thể cộng sao cho học sinh.",
  classStarsRedeemed: "Đã quy đổi sao thành điểm và reset sao.",
  classStarsRedeemFail: "Không thể quy đổi sao thành điểm.",
  classPickPercentSaved: "Đã cập nhật % random học sinh.",
  classPickPercentSaveFail: "Không thể cập nhật % random học sinh.",
  classRandomPicked: "Đã random học sinh thành công.",
  classRandomEmpty: "Lớp hiện không có học sinh đang hoạt động để random.",
};

// Hotfix chuỗi tiếng Việt bị lỗi mã hóa ở các màn hình đang dùng.
copyVi.goals = {
  ...(copyVi.goals || {}),
  status: {
    ...((copyVi.goals && copyVi.goals.status) || {}),
    done: "Hoàn thành",
    active: "Đang chạy",
    reached: "Đã đạt",
  },
  table: {
    ...((copyVi.goals && copyVi.goals.table) || {}),
    emptyGoals: "Chưa có mục tiêu nào.",
    emptyHabits: "Chưa có thói quen nào.",
  },
  dailyFocus: {
    ...((copyVi.goals && copyVi.goals.dailyFocus) || {}),
    title: "Hôm nay cần làm gì",
    subtitle: "Ưu tiên các thói quen còn thiếu quota để giữ tiến độ tuần.",
    empty: "Tuyệt vời! Bạn đã hoàn thành toàn bộ quota kỳ hiện tại.",
    action: "Điểm danh nhanh",
    remaining: "Còn {{remaining}} lượt",
  },
  weekly: {
    ...((copyVi.goals && copyVi.goals.weekly) || {}),
    saving: "Đang lưu kế hoạch tuần...",
    savedAt: "Đã lưu lúc {{time}}",
    saved: "Đã lưu kế hoạch tuần",
    error: "Lưu mục tiêu tuần thất bại",
    ready: "Sẵn sàng cập nhật mục tiêu tuần",
    currentWeek: "Tuần hiện tại",
    label: "Kế hoạch tuần {{weekKey}}",
    unsaved: "Bạn đang có thay đổi chưa lưu cho mục tiêu tuần",
  },
};

copyVi.videoPlan = {
  ...(copyVi.videoPlan || {}),
  layout: {
    ...((copyVi.videoPlan && copyVi.videoPlan.layout) || {}),
    createSubtitle: "Điền thông tin cốt lõi, sau đó dùng AI để hoàn thiện nội dung.",
  },
};

export function t(path, fallback = "") {
  if (!path) return fallback;

  const chunks = String(path).split(".");
  let cur = copyVi;

  for (const key of chunks) {
    if (cur && Object.prototype.hasOwnProperty.call(cur, key)) {
      cur = cur[key];
    } else {
      return fallback;
    }
  }

  return cur ?? fallback;
}

export function formatTemplate(template, payload = {}) {
  let out = String(template || "");
  Object.entries(payload).forEach(([k, v]) => {
    out = out.replaceAll(`{{${k}}}`, String(v ?? ""));
  });
  return out;
}
