export const appState = {
  accounts: [],
  currentUser: null,
  expTotal: 0,
  incTotal: 0,
  pendingDeleteId: null,
  pendingDeleteIncomeId: null,
  allExpenses: [],
  allIncomes: [],
  expenseFilters: { category: "all", account: "all", search: "" },
  incomeFilters: { account: "all", search: "" },
  goals: [],
  habits: [],
  habitLogsToday: [],
  videoTasks: [],
  motivation: {
    streak: 0,
    totalXp: 0,
    level: 1,
    day: { done: 0, target: 0, percent: 0 },
    week: { done: 0, target: 0, percent: 0 },
    month: { done: 0, target: 0, percent: 0 },
  },
};
